### ISSUE TITLE
Abbreviations for dropdown are irregular

### ISSUE THREAD

**Issue by thesunshade** [benmneb/pts-converter#1]
I noticed that some of the abbreviations are in lower case. This puts them out of order in the drop down:
![image](https://user-images.githubusercontent.com/82448383/150300067-138f0887-d3cc-4673-ad29-7f6d6a0b15e5.png)

As well, You have 
Th and Thi for what "should" be Thag and Thig and also tha and thi instead of Tha-ap and Thi-ap.

From what I can tell, these values are only used as labels.

**Comment by benmneb** [comment]
Thanks! I just fixed this. You might need to do a hard refresh in your browser to see the updates. 🙏

**Comment by thesunshade** [comment]
Looks great! Thank you!
