### ISSUE TITLE
New translations not added (Snp, Ud, Thi, Thag)

### ISSUE THREAD

**Issue by thesunshade** [benmneb/pts-converter#2]
I think that the Ud is completely new since you made the ap. Also now there is a complete Pali/English translation of the Snp by Bhante Sujato.

The Thag and Thig are older, so I'm not sure if there is a reason you don't include them.

Wonderful tool!

**Comment by benmneb** [comment]
Thanks! I just updated it with these translations. You might need to do a hard refresh in your browser to see them updated. 🙏

**Comment by thesunshade** [comment]
Sadhu! That's great. Thank you!
